// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as OtherJsx from "./other.jsx";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Color from "@texel/color";
import * as JsxRuntime from "react/jsx-runtime";

function mapRange(n, f) {
  return Core__Array.make(n, 0).map(function (param, i) {
              return f(i);
            });
}

function App$Palette(props) {
  var match = React.useState(function () {
        var xLen = 5;
        var yLen = 5;
        return mapRange(xLen, (function (x) {
                      var elements = mapRange(yLen, (function (y) {
                              var hex = Color.RGBToHex(Color.convert([
                                        x / xLen * 360,
                                        (y + 1) / yLen,
                                        1.0
                                      ], Color.OKHSV, Color.sRGB));
                              return {
                                      id: y.toString() + x.toString(),
                                      hex: hex
                                    };
                            }));
                      return {
                              id: x.toString(),
                              elements: elements
                            };
                    }));
      });
  var picks = match[0];
  console.log(picks);
  var len = (function (x) {
        return x.elements.length;
      })(picks[0]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: mapRange(len, (function (i) {
                              return JsxRuntime.jsx("div", {
                                          children: JsxRuntime.jsx("button", {
                                                className: "w-4 h-4 bg-blue-500 -ml-2 rounded-full"
                                              }),
                                          className: "w-10"
                                        });
                            })),
                      className: "flex flex-row"
                    }),
                picks.map(function (param) {
                      return JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("button", {
                                          className: "w-4 h-4 bg-blue-500 -mt-2 rounded-full"
                                        }),
                                    param.elements.map(function (element) {
                                          return JsxRuntime.jsx("div", {
                                                      className: "w-10 h-10 m-1",
                                                      style: {
                                                        backgroundColor: element.hex
                                                      }
                                                    }, element.id);
                                        })
                                  ],
                                  className: "flex flex-row "
                                }, param.id);
                    })
              ],
              className: "p-6"
            });
}

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(App$Palette, {
                    arr: []
                  }),
              className: "p-6 "
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
