// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Color from "@texel/color";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function ChromaStack(props) {
  var selectedElement = props.selectedElement;
  return JsxRuntime.jsx("div", {
              children: props.hues.map(function (hue) {
                    return JsxRuntime.jsx("div", {
                                children: hue.elements.map(function (e) {
                                      var hex = Color.RGBToHex(Color.convert([
                                                hue.value,
                                                e.saturation,
                                                e.lightness
                                              ], Color.OKHSL, Color.sRGB));
                                      var match = Color.convert([
                                            hue.value,
                                            e.saturation,
                                            e.lightness
                                          ], Color.OKHSL, Color.OKLCH);
                                      return JsxRuntime.jsx("div", {
                                                  children: Core__Option.mapOr(selectedElement, false, (function (x) {
                                                          return x === e.id;
                                                        })) ? "•" : null,
                                                  className: "absolute w-5 h-5 border border-black flex flex-col items-center justify-center",
                                                  style: {
                                                    backgroundColor: hex,
                                                    bottom: (match[1] / Common.chromaBound * 300 | 0).toString() + "px"
                                                  }
                                                });
                                    }),
                                className: "relative w-5"
                              });
                  }),
              className: "flex flex-row gap-1 border-black border",
              style: {
                height: (300).toString() + "px"
              }
            });
}

var ySize = 300;

var make = ChromaStack;

export {
  ySize ,
  make ,
}
/* @texel/color Not a pure module */
