// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function mapRange(n, f) {
  return Core__Array.make(n, 0).map(function (param, i) {
              return f(i);
            });
}

function bound(left, right, v) {
  return Math.max(left, Math.min(right, v));
}

var Utils = {
  mapRange: mapRange,
  bound: bound
};

var Types = {};

function hueToName(hue) {
  if (hue >= 5 && hue < 15) {
    return "rose";
  } else if (hue >= 15 && hue < 25) {
    return "crimson";
  } else if (hue >= 25 && hue < 35) {
    return "red";
  } else if (hue >= 35 && hue < 45) {
    return "vermillion";
  } else if (hue >= 45 && hue < 55) {
    return "persimmon";
  } else if (hue >= 55 && hue < 65) {
    return "orange";
  } else if (hue >= 65 && hue < 75) {
    return "pumpkin";
  } else if (hue >= 75 && hue < 85) {
    return "mango";
  } else if (hue >= 85 && hue < 95) {
    return "amber";
  } else if (hue >= 95 && hue < 105) {
    return "gold";
  } else if (hue >= 105 && hue < 115) {
    return "yellow";
  } else if (hue >= 115 && hue < 125) {
    return "citron";
  } else if (hue >= 125 && hue < 135) {
    return "pear";
  } else if (hue >= 135 && hue < 145) {
    return "chartreuse";
  } else if (hue >= 145 && hue < 155) {
    return "lime";
  } else if (hue >= 155 && hue < 165) {
    return "green";
  } else if (hue >= 165 && hue < 175) {
    return "emerald";
  } else if (hue >= 175 && hue < 185) {
    return "mint";
  } else if (hue >= 185 && hue < 195) {
    return "sea";
  } else if (hue >= 195 && hue < 205) {
    return "teal";
  } else if (hue >= 205 && hue < 215) {
    return "cyan";
  } else if (hue >= 215 && hue < 225) {
    return "pacific";
  } else if (hue >= 225 && hue < 235) {
    return "cerulean";
  } else if (hue >= 235 && hue < 245) {
    return "capri";
  } else if (hue >= 245 && hue < 255) {
    return "sky";
  } else if (hue >= 255 && hue < 265) {
    return "blue";
  } else if (hue >= 265 && hue < 275) {
    return "sapphire";
  } else if (hue >= 275 && hue < 285) {
    return "indigo";
  } else if (hue >= 285 && hue < 295) {
    return "veronica";
  } else if (hue >= 295 && hue < 305) {
    return "violet";
  } else if (hue >= 305 && hue < 315) {
    return "amethyst";
  } else if (hue >= 315 && hue < 325) {
    return "purple";
  } else if (hue >= 325 && hue < 335) {
    return "plum";
  } else if (hue >= 335 && hue < 345) {
    return "fuchsia";
  } else if (hue >= 345 && hue < 355) {
    return "magenta";
  } else if (hue >= 355 || hue < 5) {
    return "pink";
  } else {
    return "?";
  }
}

var chromaBound = 0.36;

export {
  Utils ,
  chromaBound ,
  Types ,
  hueToName ,
}
/* No side effect */
