// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "@texel/color";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function LightnessStack(props) {
  var selectedElement = props.selectedElement;
  return JsxRuntime.jsx("div", {
              children: props.hues.map(function (hue) {
                    return JsxRuntime.jsx("div", {
                                children: hue.elements.map(function (e) {
                                      var hex = Color.RGBToHex(Color.convert([
                                                hue.value,
                                                e.saturation,
                                                e.lightness
                                              ], Color.OKHSL, Color.sRGB));
                                      return JsxRuntime.jsx("div", {
                                                  children: Core__Option.mapOr(selectedElement, false, (function (x) {
                                                          return x === e.id;
                                                        })) ? "•" : null,
                                                  className: "absolute w-5 h-5 border border-black flex flex-row items-center justify-center",
                                                  style: {
                                                    backgroundColor: hex,
                                                    left: (e.lightness * 300 | 0).toString() + "px"
                                                  }
                                                });
                                    }),
                                className: "relative h-5"
                              });
                  }),
              className: "flex flex-col gap-1 border-black border",
              style: {
                width: (300).toString() + "px"
              }
            });
}

var ySize = 300;

var make = LightnessStack;

export {
  ySize ,
  make ,
}
/* @texel/color Not a pure module */
