// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Color from "@texel/color";
import * as JsxRuntime from "react/jsx-runtime";

function NameInspection(props) {
  return JsxRuntime.jsx("div", {
              children: Common.Utils.mapRange(36, (function (i) {
                      var hue = Math.imul(i, 10);
                      return JsxRuntime.jsxs("div", {
                                  children: [
                                    JsxRuntime.jsx("div", {
                                          className: "w-4 h-4",
                                          style: {
                                            backgroundColor: Color.RGBToHex(Color.convert([
                                                      hue,
                                                      1.0,
                                                      1.0
                                                    ], Color.OKHSV, Color.sRGB))
                                          }
                                        }),
                                    Common.hueToName(hue)
                                  ],
                                  className: "flex flex-row"
                                });
                    }))
            });
}

var make = NameInspection;

export {
  make ,
}
/* @texel/color Not a pure module */
