// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "@texel/color";

function adjustLchLofHex(hex, f) {
  var match = Color.convert(Color.hexToRGB(hex), Color.sRGB, Color.OKLCH);
  return Color.RGBToHex(Color.convert([
                  f(match[0]),
                  match[1],
                  match[2]
                ], Color.OKLCH, Color.sRGB));
}

function adjustLchCofHex(hex, f) {
  var match = Color.convert(Color.hexToRGB(hex), Color.sRGB, Color.OKLCH);
  return Color.RGBToHex(Color.convert([
                  match[0],
                  f(match[1]),
                  match[2]
                ], Color.OKLCH, Color.sRGB));
}

export {
  adjustLchLofHex ,
  adjustLchCofHex ,
}
/* @texel/color Not a pure module */
